# Default values for conan-ci.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hostName: conan-ci

mysql:
  auth:
    rootPassword: secret
    database: conan-ci
  # primary:
  #   persistence:
  #     existingClaim: mysql

phpmyadmin:
  db:
    chartName: mysql

mtu: 1450
insecureRegistries: []

services:
  - name: public
    pingUrl: /api/v1/ping
    # python -c 'import base64, os; print(base64.b64encode(os.urandom(16)))'
    secretKey: MDAwMDAwMDAwMDAwMDAwMA==
    password: paSSw0rd
  - name: scheduler
  - name: crawler
  - name: frontend
  - name: linux-agent
    docker: true
    image: agent
    replicas: 1

windows:
  image: localhost:5000/windows20h2:latest
  agents:
    - name: one
      image: agent
