# Default values for sonja.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hostName: sonja

mysql:
  auth:
    rootPassword: secret
    database: sonja

mtu: 1450
insecureRegistries: []

auth:
  # python -c 'import base64, os; print(base64.b64encode(os.urandom(16)))'
  secretKey: MDAwMDAwMDAwMDAwMDAwMA==
  user: user
  password: paSSw0rd

services:
  - name: public
    pingUrl: /api/v1/ping
  - name: scheduler
  - name: crawler
  - name: frontend
  - name: linux-agent
    docker: true
    image: agent
    replicas: 1

windows:
  image: localhost:5000/windows20h2:latest
  agents:
    - name: one
      image: agent
