{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sonja.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "sonja.fullname" $ }}-{{ .name }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ template "sonja.fullname" $ }}-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ template "sonja.fullname" $ }}-{{ .name }}
    spec:
      containers:
      - name:  {{ .name }}
{{- if .image }}
        image: uboot/{{ .image }}:latest
{{- else }}
        image: uboot/{{ .name }}:latest
{{- end }}
        livenessProbe:
          httpGet:
            path: {{ .pingUrl | default "/ping" }}
            port: 8080
          initialDelaySeconds: 300
        env:
        - name: MYSQL_URL
          value: {{ $.Release.Name }}-mysql
        - name: MYSQL_ROOT_PASSWORD
          value: {{ $.Values.mysql.auth.rootPassword }}
        - name: SONJA_AGENT_OS
          value: Linux
        - name: SONJA_MTU
          value: "{{ $.Values.mtu | default 1500 }}"
        - name: SONJA_CRAWLER_URL
          value: {{ template "sonja.fullname" $ }}-crawler
        - name: SONJA_SCHEDULER_URL
          value: {{ template "sonja.fullname" $ }}-scheduler
        - name: SONJA_LINUXAGENT_URL
          value: {{ template "sonja.fullname" $ }}-linux-agent
        - name: SONJA_WINDOWSAGENT_URL
          value: {{ template "sonja.fullname" $ }}-windows-agent
        - name: SONJA_INITIAL_USER
          value: {{ $.Values.auth.user }}
        - name: SONJA_INITIAL_PASSWORD
          value: {{ $.Values.auth.password }}
        - name: SONJA_SECRET_KEY
          value: {{ $.Values.auth.secretKey }}
{{- if .password }}
        - name: PASSWORD
          value: {{ .password }}
{{- end }}
{{- if .docker }}
        - name: DOCKER_HOST
          value: 127.0.0.1:2375
{{- end }}
{{- if .docker }}
      - name: docker
        image: docker:19.03.12-dind
        command: 
        - "dockerd"
        - "--mtu"
        - {{ $.Values.mtu | quote }}
{{- range $.Values.insecureRegistries }}
        - "--insecure-registry"
        - {{ . | quote }}
{{- end }}
        - "-H"
        - "tcp://"
        securityContext:
          privileged: true
{{- end }}
---
{{- end }}
{{- range .Values.windows.agents }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sonja.fullname" $ }}-windows-agent-{{ .name }}
  labels:
    app: {{ template "sonja.fullname" $ }}-windows-agent
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ template "sonja.fullname" $ }}-windows-agent
      deployment: {{ template "sonja.fullname" $ }}-windows-agent-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ template "sonja.fullname" $ }}-windows-agent
        deployment: {{ template "sonja.fullname" $ }}-windows-agent-{{ .name }}
    spec:
      containers:
      - name:  windows-agent
{{- if .image }}
        image: uboot/{{ .image }}:latest
{{- else }}
        image: uboot/{{ .name }}:latest
{{- end }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 300
        env:
        - name: MYSQL_URL
          value: {{ $.Release.Name }}-mysql
        - name: MYSQL_ROOT_PASSWORD
          value: {{ $.Values.mysql.auth.rootPassword }}
        - name: SONJA_AGENT_OS
          value: Windows
        - name: SONJA_MTU
          value: "{{ $.Values.mtu | default 1500 }}"
        - name: SONJA_CRAWLER_URL
          value: {{ template "sonja.fullname" $ }}-crawler
        - name: SONJA_SCHEDULER_URL
          value: {{ template "sonja.fullname" $ }}-scheduler
        - name: SONJA_LINUXAGENT_URL
          value: {{ template "sonja.fullname" $ }}-linux-agent
        - name: SONJA_WINDOWSAGENT_URL
          value: {{ template "sonja.fullname" $ }}-windows-agent
        - name: DOCKER_HOST
          value: {{ template "sonja.fullname" $ }}-windows-docker-{{ .name }}:2375
---
{{- end }}
