apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "sonja.fullname" $ }}-ingress-frontend
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.hostName }}
    secretName: {{ .Release.Name }}
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "sonja.fullname" $ }}-frontend
            port: 
              number: 8080
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: {{ template "sonja.fullname" $ }}-public
            port: 
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "sonja.fullname" $ }}-ingress-phpmyadmin
  annotations:
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/phpmyadmin/(.*) /$1"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - path: /phpmyadmin
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-phpmyadmin
            port: 
              number: 80
