version: 1
formatters:
  simple:
#    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    format: '%(levelname)s %(asctime)s %(filename)s:%(lineno)d %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  short:
    format: '%(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
loggers:
  sonja:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]