version: 1
formatters:
  simple:
#    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    format: '%(levelname)s %(asctime)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  short:
    format: '%(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  short:
    class: logging.StreamHandler
    level: DEBUG
    formatter: short
    stream: ext://sys.stdout
filters:
  ping:
    (): sonja.config.PingFilter
loggers:
  sonja:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [short]
    filters: [ping]
    propagate: no
root:
  level: INFO
  handlers: [console]