openapi: 3.0.0
info:
  title: Agent
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths:
  /ping:
    get:
      summary: ping the service
      operationId: ping
      responses:
        "200":
          description: success
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /process-builds:
    get:
      summary: Process new builds
      operationId: process_builds
      responses:
        "200":
          description: success
      x-openapi-router-controller: swagger_server.controllers.default_controller
components: {}

