openapi: 3.0.0
info:
  title: Conan CI Crawler
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths:
  /ping:
    get:
      summary: ping the service
      operationId: ping
      responses:
        "200":
          description: success
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /process-repo/{repoId}:
    get:
      summary: scan repos for new commits
      operationId: process_repo
      parameters:
      - name: repoId
        in: path
        description: repo ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: success
        "400":
          description: invalid ID supplied
        "404":
          description: repo not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
components: {}

